Proposal: Charter for the DID Resolution WG (as a replacement to current proposal) to continue the work of DID 1.0
w3c/did-wg-charter pull request #30
Opened 2023-03-13 19:33 UTC by ChristopherA

As per:

#24 (@brentzundel)
> During our F2F meeting in Vancouver, many participants voiced support for beginning to specify DID Resolution.

#28 (@ChristopherA)
> Shouldn't we reconsider chartering this working group and instead focus on chartering a DID Resolver WG?"

https://github.com/w3c/did-wg-charter/pull/27#issuecomment-1382091353 (@TallTed)
> @ChristopherA — I think your suggestion of "chartering ... a DID-Resolution working group first, rather than continuing to work on a DID 2.0 WG charter" along with your other concerns as stated here would be better raised as one or more independent issues, as they are not just about Deliverables (as this issue is), but rather about the entirety of this draft DID 2.0 WG charter.

https://github.com/w3c/did-wg-charter/pull/27#issuecomment-1370900227 (@jandrieu)
> Frankly, until we have DID Resolution addressed, we have no business standardizing specific DID methods, as made evident by the lack of methods suitable at this stage. When TBL created the Web, the standard was the data model and protocols, NOT the personnel directory application he built at CERN. It is the intersection of the myriad of DID methods that we should be standardizing, not any particular method. Not at this time.

2023-03-14 01:49 UTC, TallTed requested changes
Minor tweaks

2023-03-14 01:49 UTC, TallTed commented on index.html
> +            <li>extension points for method-specific Resolution and Dereferencing.</li>
```suggestion
            <li>common syntax and semantics for DID URL components such as queries, paths, and fragments</li>
            <li>extension points for method-specific Resolution and Dereferencing</li>
```

2023-03-14 01:49 UTC, TallTed commented on index.html
> +        <p>In addition, the following, non-normative Working Group Notes will also be maintained by the Working Group.</p>
```suggestion
        <p>In addition, the following non-normative Working Group Notes will also be maintained by the Working Group.</p>
```

2023-03-14 01:49 UTC, TallTed commented on index.html
> +                  href="https://www.w3.org/community/credentials/charter/">https://www.w3.org/community/credentials/charter/</a>.
```suggestion
                Latest publication: <i>2023-01-18</i>
                <br>
                Reference Document: <a
                  href="https://w3c-ccg.github.io/did-resolution/">https://w3c-ccg.github.io/did-resolution/</a>
                <br>
                Produced under Credentials Community Group Charter: <a
                  href="https://www.w3.org/community/credentials/charter/">https://www.w3.org/community/credentials/charter/</a>
```

2023-03-14 15:28 UTC, brentzundel requested changes
It was never my understanding that a DID Resolution WG would replace the DID WG. I do not support that course of action.
If folks are interested in pursuing a DID Resolution WG Charter separate from the DID WG Charter, the place to do it is not here.

For guidance on the process of developing a charter at W3C, please review the [W3C Process Document](https://www.w3.org/2021/Process-20211102/#WGCharterDevelopment).

The chairs of the DID WG still intend to submit a charter for maintaining the DID Specification. If a DID Resolution WG Charter is drafted and will be pursued, then we will remove DID Resolution from the scope of this charter.

2023-03-14 17:29 UTC, pchampin commented
To complement @brentzundel's comment above, what is the intent here?

1. to propose to renew the old WG with another name, and a slightly different charter?
2. to not renew the DID WG, but to propose a supposedly brand new WG who will, among other things, take over the maintenance the recommendation of the old DID WG?
3. to propose the DID Resolution WG in parallel with the DID WG?

I don't think we can get away with 1 or 2, which in essence, recreate the DID WG, and therefore still makes us liable to the director's advice in his decision about the formal objections.

As for 3, this would need the removal from this new proposed charter of the part about maintaining the existing specs. For this we still need a DID WG who, again, will have to respond one way or another to the director's advice. Granted, in that scenario, the response could be "we defer to the DID Resolution WG", but will this fly with the AC?

2023-03-14 18:06 UTC, jandrieu commented
> The chairs of the DID WG still intend to submit a charter for maintaining the DID Specification.

Great. I'd love to see the follow through on consensus development that was promised in https://github.com/w3c/did-wg-charter/pull/27#issuecomment-1402233965
> Whichever PR achieves greater consensus, as determined by the chairs of the current DID WG, will be merged.

There are now three PRs seeking to find the "best consensus" of the current DID WG, which by W3C process means the option with the weakest technical objections. https://www.w3.org/2021/Process-20211102/#managing-dissent 

I look forward to the chairs calling for technical objections to all three PRs. I have raised my objections to #27 and further discussed them in #29. I would support #29 with the requested changes I've offered in my review. I would also support #30 as is. For clarity, I oppose #27 and will file a formal appeal if the chairs ignore consensus and put that charter forward on the grounds that the chairs have not served the W3C commitment to consensus in this Working Group.

@brentzundel also said
> If a DID Resolution WG Charter is drafted and will be pursued, then we will remove DID Resolution from the scope of this charter.

Unfortunately, Brent, I don't believe it is under your authority to arbitrarily pick and choose what parts of these Charters are proposed by the Working Group. To quote the W3C Process:
>  To promote consensus, the W3C process requires Chairs to ensure that groups consider all legitimate views and objections, and endeavor to resolve them, whether these views and objections are expressed by the active participants of the group or by others (e.g., another W3C group, a group in another organization, or the general public).

As I mentioned in my previous answer, the PR that Christopher has offered was in response to a specific request by DID WG members and @brentzundel  to produce an alternative option for consideration. Now that we've done the work, I expect it to receive the same respect and due process as the contributions of any member of the WG.

Brent, do you have technical objections to the group putting forth a DID Resolution WG Charter instead of a DID WG Charter?

2023-03-14 18:21 UTC, brentzundel commented
The technical objection to changing this charter into a charter for DID Resolution was outlined by @pchampin above.

2023-03-14 18:33 UTC, jandrieu commented
> To complement @brentzundel's comment above, what is the intent here?
> 
> 2. to not renew the DID WG, but to propose a supposedly brand new WG who will, among other things, take over the maintenance the recommendation of the old DID WG?

This is the proposal. Many members have expressed the concern that the next DID WG charter *MUST* have DID Methods in scope. In response to that concern, the proposal is to change the name. Instead of creating a DID WG Charter, create a DID Resolution WG Charter, so that we can advance the work in the most reasonable terms. Rushing to define DID methods when no such DID method is even put forward is running before we can walk. 
 
> I don't think we can get away with 1 or 2, which in essence, recreate the DID WG, and therefore still makes us liable to the director's advice in his decision about the formal objections.

I argue that #2 is not recreating the DID WG as it is not chartered for class 4 changes and *is* chartered for a focus on a new specification, Resolution. During the development of that specification, we may learn of changes required in DID Core to support better interoperability and which suggests the DID Resolution WG is the best place to maintain DID Core, especially given that there will not be a DID WG should we take this proposal.

If you are arguing that this WG is only able to, and MUST, propose a single DID WG Charter, I find that incredulous. There is no scope stated within the current charter to that effect: there is no formal justification for such a limitation. If that point ends up being the primary debate, I'm happy to put that before the organization. It is unconscionable for the Director to bind the future charters of this working group, in response to a formal objection to a Candidate Recommendation from this WG. Outsiders to the group demanding what the group do, or do not do, to advance the work does not make for effective standards development. 

> As for 3, this would need the removal from this new proposed charter of the part about maintaining the existing specs. For this we still need a DID WG who, again, will have to respond one way or another to the director's advice. Granted, in that scenario, the response could be "we defer to the DID Resolution WG", but will this fly with the AC?

Several members (including @sakurann and @OR13)  have voiced concern that the group does not have enough implementation experience to advance the current DID WG Charter. I agree. Which suggests we do NOT need a DID WG. Certainly not as proposed. And certainly not at this time. The WG doesn't have consensus to do that work in that manner. The idea that we absolutely need a DID WG is, on its face, untenable. If we're not ready for a DID WG, then we shouldn't propose such a thing.

2023-03-14 18:38 UTC, jandrieu commented
> The technical objection to changing this charter into a charter for DID Resolution was outlined by @pchampin above.

Could you clarify?

I'm not trying to be obtuse here, but what I read in @pchampin's comments are purely political considerations. What are the technical objections?

2023-03-14 19:31 UTC, OR13 commented
IMO the simplest solution is remove "specific did method documents" from the current charter, I would expect any charter that contained authorization for the DID WG to create "specific did methods" to not pass... based on the threads that I have read.

Most folks seem favorable to defining did resolution and dereferencing and unfavorable to defining specific did methods.

JSON-LD defined document loading: https://www.w3.org/TR/json-ld11/#loading-documents

It did not define "serving JSON-LD over HTTP from web servers meeting the approval of the working group"... aka... a specific method of document loading.

2023-03-15 22:18 UTC, brentzundel commented
The DID WG chairs have met. We have concluded that merging PR #27 will produce a charter that best represents the consensus of the DID Working Group participants over the past year.
Despite many, many discussions, no other proposal within the group has garnered as much support as this one has for the creation of a new DID Working Group, which will focus on maintaining Decentralized Identifiers (DIDs) v1.0 and publishing errata updates to that specification. The charter also permits the next DID WG to begin work on DID Methods and DID Resolution, but does not require it, e.g., the group that forms may do as much or as little work on these optional topics as desired.

Now, regarding the other open PRs, #29 and #30:
 1. The predominant concern raised has been with the inclusion of DID Methods as optional work in this charter. The inclusion of DID Methods in the next chartered DID WG was part of the W3C Director’s decision to overturn the Formal Objections raised against the publication of Decentralized Identifiers (DIDs) v1.0. The chairs feel that that decision represents the consensus of the W3C and as such the inclusion of DID Methods as optional work in this charter is absolutely necessary. So we have concluded that PR #29 is no longer relevant to this discussion.  We are leaving it open for comments, but they will not change the decision at this point.
2. There have been suggestions for an alternative group focused exclusively on DID Resolution. We support the effort to create a DID Resolution Working Group that focuses entirely on DID Resolution, as that will strongly support the work of the DID Working Group, which must focus on the DID Specification.  We encourage the proponents to develop their proposal and present it to W3M and the AC Forum as a new Working Group.  However, because it would not be a DID Working Group, we have concluded that PR #30 is no longer relevant to this conversation.  We are leaving it open for those who wish to continue designing a separate DID Resolution-focused WG, but we do not expect such work to change the decision at this point.

2023-03-17 20:25 UTC, OR13 commented
I suggest closing this PR.

2026-07-10 13:50 UTC, pchampin commented
Closing this very old PR

2026-07-10 13:50 UTC, closed without merging