Changes after the wg call on Aug 3
w3c/did-wg-charter pull request #6
Opened 2021-08-04 09:23 UTC by iherman

I have tried to collect the proposed changes on the charter from the meeting minutes of Aug 3. The changes are:

- Made it explicit that
    - the WG is allowed to make class 1,2, and 3 level changes on the spec
    - Class 4 level changes are out of scope
- Removed, from the "out of scope" section reference to method specifications (ie, it is now possible to publish a note on, say, `did:web`)
- Added a remark to the formal deliverable entry on registries that the WG may convert the document into a W3C Registry Document, if the new process is accepted
- Removed the JSON-LD WG from the list of coordination.

See the [diff file](https://tinyurl.com/e3rdupz4) for the changes.

What is missing is a review and a PR of the full coordination session, in particular a right reference to the IETF security group that was discussed.

2021-08-04 09:29 UTC, iherman commented
I did not realize that @brentzundel also includes some PR-s, and there is some duplication (sorry @brentzundel). The removal of the "out of scope" section is a direct duplication for #4, #5 and #3 are complementary and have been merged into the main branch.

2021-08-04 16:17 UTC, brentzundel approved these changes

2021-08-04 17:31 UTC, jandrieu requested changes

2021-08-04 17:31 UTC, jandrieu commented on index.html
> +            <a href="https://www.w3.org/TR/did-rubric/">Decentralized Characteristics Rubric</a> <i class=todo>(Note: this link is currently 404, the planned publication for this note is mid-August)<
The title of the rubric changed due to the expansion of scope beyond just decentralization.
```suggestion
            <a href="https://www.w3.org/TR/did-rubric/">DID Method Rubric</a> <i class=todo>(Note: this link is currently 404, the planned publication for this note is mid-August)</i>
```

2021-08-04 21:14 UTC, msporny approved these changes
LGTM, I'm writing a PR right now on top of this for the coordination sections.

EDIT: Done, PR is here -- https://github.com/w3c/did-wg-charter/pull/7 (which merges into this branch)

2021-08-05 03:49 UTC, kdenhartog approved these changes

2021-08-05 06:47 UTC, iherman commented
Merging this to move ahead as quickly as possible.

2021-08-05 06:48 UTC, merged